name: demo

on:
  push:
    branches:
      # Push events on master branch
      - master
      - 'pr/*'
    paths:
      - 'demo/**'
  pull_request:
    branches:
      - 'pr/*'
    # paths:
      #- 'demo/**'
env:
  SAMPLE_PATH: demo

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Generate cache key
      run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

    - name: Gradle Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/modules-*
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/build-cache-*
        key: gradle-${{ hashFiles('checksum.txt') }}

    - name: NDK Cache
      id: ndk-cache
      uses: actions/cache@v2
      with:
        path: ${ANDROID_HOME}/ndk/
        key: ndk-cache-21.3.6528147-v2

    # https://github.com/actions/virtual-environments/issues/643
    # NOTE : `NDK Cache - Key` has to be changed while changing the ndk version
    - name: Install NDK
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"

    # - name: Install Gradle Wrapper
    #   run: gradle wrapper

    - name: Build Demo
      run: ./gradlew build

    - name: Upload Demo APK
      uses: actions/upload-artifact@v2
      with:
        name: build-outputs
        path: ${{ env.SAMPLE_PATH }}/app/build/outputs
        retention-days: 5

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: ${{ env.SAMPLE_PATH }}/app/build/reports
        retention-days: 5

   # - name: Run Spotless Check
   #   run: ./gradlew spotlessCheck

   #  - name: Run Detekt
   #    run: ./gradlew detekt

   #  - name: Run Lint
   #    run: ./gradlew lintDebug

    - name: Install Gems
      run: |
        gem install bundler
        bundle install

    #
#    - name: Run Danger
#      env:
#        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
#      run: bundle exec danger
